# Site settings
title: Gibberich
description: Modern-Blog Outlet of a dreamer
keywords: Modern, Blogging, Fun
author: Akshay Elangovan
baseurl: "giberich.com" # the subpath of your site, e.g. /blog/
url: "gibberich.com" # the base hostname & protocol for your site
